
# Based on https://github.com/mathworks/Simulink-Model-Comparison-for-GitHub-Pull-Requests
# Removed tests for initial set-up of this action

name: PushToMain - Diff to Ancestor, Publish and attach Report, and Run Project Tests

# Controls when the workflow will run
on: 
  # Triggers the workflow on push events ...
  push:
  #  branches: [ main ] # ...but only for the main branch
    paths:
      - '**.slx' # ...and only if an .slx file is included
      - '**.yml' # ...and only if an .yml file is included
      - '**.m' # ...and only if an .m file is included
      - '**.mldatx' # ...and only if an .mldatx (SL Test) file is included
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  my-job:
    name: Diff to Ancestor, Publish and attach Report, and Run Project Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
         fetch-depth: 0
      - name: Start Display Server
        run: |
         sudo apt-get install -y xvfb
         Xvfb :99 &
         export DISPLAY=:99
         echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
         release: R2025b
         products: >
            Simulink
            Simulink_Test
            Audio_Toolbox

      - name: Compare Models to Ancestors
        uses: matlab-actions/run-command@v2
        with:
          command: lastpush="${{ github.event.before }}", addpath("helper"), diffGitHub_push(lastpush)
      - name: Upload Comparison SLX
        uses: actions/upload-artifact@v4
        with:
           name: slxfiles
           path: ${{ github.workspace }}/modelscopy/*.slx
      - name: Upload Comparison Reports
        uses: actions/upload-artifact@v4
        with:
           name: diffreports
           path: ${{ github.workspace }}/*.html
      - name: Run All Project Tests
        uses: matlab-actions/run-command@v2
        with:
          command: runtests

#   Copyright 2022-2024 The MathWorks, Inc.
